import { _ } from './elem-factory';
import { bind } from './lib';

export let a: typeof _.a ;
export let abbr: typeof _.abbr;
export let address: typeof _.address;
export let area: typeof _.area;
export let article: typeof _.article;
export let aside: typeof _.aside;
export let audio: typeof _.audio;
export let b: typeof _.b;
export let base: typeof _.base;
export let bdi: typeof _.bdi;
export let bdo: typeof _.bdo;
export let big: typeof _.big;
export let blockquote: typeof _.blockquote;
export let body: typeof _.body;
export let br: typeof _.br;
export let button: typeof _.button;
export let canvas: typeof _.canvas;
export let caption: typeof _.caption;
export let cite: typeof _.cite;
export let code: typeof _.code;
export let col: typeof _.col;
export let colgroup: typeof _.colgroup;
export let data: typeof _.data;
export let datalist: typeof _.datalist;
export let dd: typeof _.dd;
export let del: typeof _.del;
export let details: typeof _.details;
export let dfn: typeof _.dfn;
export let dialog: typeof _.dialog;
export let div: typeof _.div;
export let dl: typeof _.dl;
export let dt: typeof _.dt;
export let em: typeof _.em;
export let embed: typeof _.embed;
export let fieldset: typeof _.fieldset;
export let figcaption: typeof _.figcaption;
export let figure: typeof _.figure;
export let footer: typeof _.footer;
export let form: typeof _.form;
export let h1: typeof _.h1;
export let h2: typeof _.h2;
export let h3: typeof _.h3;
export let h4: typeof _.h4;
export let h5: typeof _.h5;
export let h6: typeof _.h6;
export let head: typeof _.head;
export let header: typeof _.header;
export let hgroup: typeof _.hgroup;
export let hr: typeof _.hr;
export let html: typeof _.html;
export let i: typeof _.i;
export let iframe: typeof _.iframe;
export let img: typeof _.img;
export let input: typeof _.input;
export let ins: typeof _.ins;
export let kbd: typeof _.kbd;
export let keygen: typeof _.keygen;
export let label: typeof _.label;
export let legend: typeof _.legend;
export let li: typeof _.li;
export let link: typeof _.link;
export let main: typeof _.main;
export let map: typeof _.map;
export let mark: typeof _.mark;
export let menu: typeof _.menu;
export let menuitem: typeof _.menuitem;
export let meta: typeof _.meta;
export let meter: typeof _.meter;
export let nav: typeof _.nav;
export let noscript: typeof _.noscript;
export let object: typeof _.object;
export let ol: typeof _.ol;
export let optgroup: typeof _.optgroup;
export let option: typeof _.option;
export let output: typeof _.output;
export let p: typeof _.p;
export let param: typeof _.param;
export let picture: typeof _.picture;
export let pre: typeof _.pre;
export let progress: typeof _.progress;
export let q: typeof _.q;
export let rp: typeof _.rp;
export let rt: typeof _.rt;
export let ruby: typeof _.ruby;
export let s: typeof _.s;
export let samp: typeof _.samp;
export let search: typeof _.search;
export let slot: typeof _.slot;
export let script: typeof _.script;
export let section: typeof _.section;
export let select: typeof _.select;
export let small: typeof _.small;
export let source: typeof _.source;
export let span: typeof _.span;
export let strong: typeof _.strong;
export let style: typeof _.style;
export let sub: typeof _.sub;
export let summary: typeof _.summary;
export let sup: typeof _.sup;
export let table: typeof _.table;
export let tbody: typeof _.tbody;
export let td: typeof _.td;
export let textarea: typeof _.textarea;
export let tfoot: typeof _.tfoot;
export let th: typeof _.th;
export let thead: typeof _.thead;
export let time: typeof _.time;
export let title: typeof _.title;
export let tr: typeof _.tr;
export let track: typeof _.track;
export let u: typeof _.u;
export let ul: typeof _.ul;
export let _var: typeof _.var;
export let video: typeof _.video;
export let wbr: typeof _.wbr;
export let svg: typeof _.svg;
export let animate: typeof _.animate;
export let animateMotion: typeof _.animateMotion;
export let animateTransform: typeof _.animateTransform;
export let circle: typeof _.circle;
export let clipPath: typeof _.clipPath;
export let defs: typeof _.defs;
export let desc: typeof _.desc;
export let ellipse: typeof _.ellipse;
export let feBlend: typeof _.feBlend;
export let feColorMatrix: typeof _.feColorMatrix;
export let feComponentTransfer: typeof _.feComponentTransfer;
export let feComposite: typeof _.feComposite;
export let feConvolveMatrix: typeof _.feConvolveMatrix;
export let feDiffuseLighting: typeof _.feDiffuseLighting;
export let feDisplacementMap: typeof _.feDisplacementMap;
export let feDistantLight: typeof _.feDistantLight;
export let feDropShadow: typeof _.feDropShadow;
export let feFlood: typeof _.feFlood;
export let feFuncA: typeof _.feFuncA;
export let feFuncB: typeof _.feFuncB;
export let feFuncG: typeof _.feFuncG;
export let feFuncR: typeof _.feFuncR;
export let feGaussianBlur: typeof _.feGaussianBlur;
export let feImage: typeof _.feImage;
export let feMerge: typeof _.feMerge;
export let feMergeNode: typeof _.feMergeNode;
export let feMorphology: typeof _.feMorphology;
export let feOffset: typeof _.feOffset;
export let fePointLight: typeof _.fePointLight;
export let feSpecularLighting: typeof _.feSpecularLighting;
export let feSpotLight: typeof _.feSpotLight;
export let feTile: typeof _.feTile;
export let feTurbulence: typeof _.feTurbulence;
export let filter: typeof _.filter;
export let foreignObject: typeof _.foreignObject;
export let g: typeof _.g;
export let image: typeof _.image;
export let line: typeof _.line;
export let linearGradient: typeof _.linearGradient;
export let marker: typeof _.marker;
export let mask: typeof _.mask;
export let metadata: typeof _.metadata;
export let mpath: typeof _.mpath;
export let path: typeof _.path;
export let pattern: typeof _.pattern;
export let polygon: typeof _.polygon;
export let polyline: typeof _.polyline;
export let radialGradient: typeof _.radialGradient;
export let rect: typeof _.rect;
export let set: typeof _.set;
export let stop: typeof _.stop;
export let _switch: typeof _.switch;
export let symbol: typeof _.symbol;
export let text: typeof _.text;
export let textPath: typeof _.textPath;
export let tspan: typeof _.tspan;
export let use: typeof _.use;
export let view: typeof _.view;

function bindWithElems(factory: Parameters<typeof bind>[0]) {
    bind(factory);
    a = _.a;
    abbr = _.abbr;
    address = _.address;
    area = _.area;
    article = _.article;
    aside = _.aside;
    audio = _.audio;
    b = _.b;
    base = _.base;
    bdi = _.bdi;
    bdo = _.bdo;
    big = _.big;
    blockquote = _.blockquote;
    body = _.body;
    br = _.br;
    button = _.button;
    canvas = _.canvas;
    caption = _.caption;
    cite = _.cite;
    code = _.code;
    col = _.col;
    colgroup = _.colgroup;
    data = _.data;
    datalist = _.datalist;
    dd = _.dd;
    del = _.del;
    details = _.details;
    dfn = _.dfn;
    dialog = _.dialog;
    div = _.div;
    dl = _.dl;
    dt = _.dt;
    em = _.em;
    embed = _.embed;
    fieldset = _.fieldset;
    figcaption = _.figcaption;
    figure = _.figure;
    footer = _.footer;
    form = _.form;
    h1 = _.h1;
    h2 = _.h2;
    h3 = _.h3;
    h4 = _.h4;
    h5 = _.h5;
    h6 = _.h6;
    head = _.head;
    header = _.header;
    hgroup = _.hgroup;
    hr = _.hr;
    html = _.html;
    i = _.i;
    iframe = _.iframe;
    img = _.img;
    input = _.input;
    ins = _.ins;
    kbd = _.kbd;
    keygen = _.keygen;
    label = _.label;
    legend = _.legend;
    li = _.li;
    link = _.link;
    main = _.main;
    map = _.map;
    mark = _.mark;
    menu = _.menu;
    menuitem = _.menuitem;
    meta = _.meta;
    meter = _.meter;
    nav = _.nav;
    noscript = _.noscript;
    object = _.object;
    ol = _.ol;
    optgroup = _.optgroup;
    option = _.option;
    output = _.output;
    p = _.p;
    param = _.param;
    picture = _.picture;
    pre = _.pre;
    progress = _.progress;
    q = _.q;
    rp = _.rp;
    rt = _.rt;
    ruby = _.ruby;
    s = _.s;
    samp = _.samp;
    search = _.search;
    slot = _.slot;
    script = _.script;
    section = _.section;
    select = _.select;
    small = _.small;
    source = _.source;
    span = _.span;
    strong = _.strong;
    style = _.style;
    sub = _.sub;
    summary = _.summary;
    sup = _.sup;
    table = _.table;
    tbody = _.tbody;
    td = _.td;
    textarea = _.textarea;
    tfoot = _.tfoot;
    th = _.th;
    thead = _.thead;
    time = _.time;
    title = _.title;
    tr = _.tr;
    track = _.track;
    u = _.u;
    ul = _.ul;
    _var = _.var;
    video = _.video;
    wbr = _.wbr;
    svg = _.svg;
    animate = _.animate;
    animateMotion = _.animateMotion;
    animateTransform = _.animateTransform;
    circle = _.circle;
    clipPath = _.clipPath;
    defs = _.defs;
    desc = _.desc;
    ellipse = _.ellipse;
    feBlend = _.feBlend;
    feColorMatrix = _.feColorMatrix;
    feComponentTransfer = _.feComponentTransfer;
    feComposite = _.feComposite;
    feConvolveMatrix = _.feConvolveMatrix;
    feDiffuseLighting = _.feDiffuseLighting;
    feDisplacementMap = _.feDisplacementMap;
    feDistantLight = _.feDistantLight;
    feDropShadow = _.feDropShadow;
    feFlood = _.feFlood;
    feFuncA = _.feFuncA;
    feFuncB = _.feFuncB;
    feFuncG = _.feFuncG;
    feFuncR = _.feFuncR;
    feGaussianBlur = _.feGaussianBlur;
    feImage = _.feImage;
    feMerge = _.feMerge;
    feMergeNode = _.feMergeNode;
    feMorphology = _.feMorphology;
    feOffset = _.feOffset;
    fePointLight = _.fePointLight;
    feSpecularLighting = _.feSpecularLighting;
    feSpotLight = _.feSpotLight;
    feTile = _.feTile;
    feTurbulence = _.feTurbulence;
    filter = _.filter;
    foreignObject = _.foreignObject;
    g = _.g;
    image = _.image;
    line = _.line;
    linearGradient = _.linearGradient;
    marker = _.marker;
    mask = _.mask;
    metadata = _.metadata;
    mpath = _.mpath;
    path = _.path;
    pattern = _.pattern;
    polygon = _.polygon;
    polyline = _.polyline;
    radialGradient = _.radialGradient;
    rect = _.rect;
    set = _.set;
    stop = _.stop;
    _switch = _.switch;
    symbol = _.symbol;
    text = _.text;
    textPath = _.textPath;
    tspan = _.tspan;
    use = _.use;
    view = _.view;
}

export { componentFactoryFactory as $ } from './lib';
export { bindWithElems as bind }
